# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MenuProfile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MenuProfile
  pod 'Alamofire'

  target 'MenuProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MenuProfileUITests' do
    # Pods for testing
  end

end
