# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alura Ponto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alura Ponto
  pod 'Alamofire'

end
